#!/bin/sh

# Provides:          tomcat7
# Required-Start:    $local_fs $remote_fs $network
# Required-Stop:     $local_fs $remote_fs $network
# Should-Start:      $named
# Should-Stop:       $named
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start Tomcat.
# Description:       Start the Tomcat servlet engine.

RETVAL='0'

case $1 in
start)
  echo 'Starting Tomcat:'
  /var/lib/tomcat/bin/startup.sh
  ;;
stop)
  echo 'Stopping Tomcat:'
  /var/lib/tomcat/bin/shutdown.sh
  ;;
restart)
  $0 stop
  $0 start
  ;;
*)
  echo "Usage: $0 {start|stop|restart}"
  RETVAL='1'
esac

exit $RETVAL
